/*
 * NT.Fiscal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using NT.Fiscal.Models;

namespace NT.Fiscal.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class FiscalApiController : ControllerBase
    {
        /// <summary>
        /// Checks if the service is running
        /// </summary>

        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/api/v1/echo")]
        public virtual IActionResult Echo()
        {
            return StatusCode(200, default(string));
        }

        /// <summary>
        /// Send a receipt to the fiscal service
        /// </summary>

        /// <param name="receiptId">id of the receipt</param>
        /// <param name="data"></param>
        /// <response code="200"></response>
        [HttpPost]
        [Route("/api/v1/receipts/{receiptId}")]
        public virtual SendReceiptResponse SendReceipt([FromRoute][Required]string receiptId, [FromBody]SendReceiptRequest data)
        {
            return new SendReceiptResponse(); //StatusCode(200, default(SendReceiptResponse));
        }
    }
}