/*
 * Nt.Fiscal
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using Nt.Fiscal.Models;
using System.ComponentModel.DataAnnotations;

namespace Nt.Fiscal.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class FiscalApiController : ControllerBase
    {
        /// <summary>
        /// Checks if the service is running
        /// </summary>

        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/api/v1/check/service")]
        public virtual IActionResult CheckService()
        {
            return StatusCode(200, "Service is running");
        }

        /// <summary>
        /// Checks if the provider is configured correctly
        /// </summary>
        [HttpGet]
        [Route("/api/v1/check/provider")]
        public virtual CheckProviderResponse CheckProvider()
        {
            CheckProviderResponse response = Nt.Fiscal.NtFiscal.FiscalProvider.CheckProvider();
            return response;
        }

        /// <summary>
        /// Send a receipt to the fiscal service
        /// </summary>
        /// <param name="receiptId">id of the receipt</param>
        /// <param name="data"></param>
        [HttpPost]
        [Route("/api/v1/receipts/{receiptId}")]
        [Produces("application/json")]
        public virtual SendReceiptResponse SendReceipt([FromRoute][Required]string receiptId, [FromBody]SendReceiptRequest data)
        {
            SendReceiptResponse response = Nt.Fiscal.NtFiscal.FiscalProvider.SendReceipt(data);
            return response;
        }
    }
}