/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Os.Server.Models
{
    /// <summary>
    /// Gets or Sets FullPaymentOnlyMode
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum FullPaymentOnlyMode
    {

        /// <summary>
        /// Enum TableEnum for table
        /// </summary>
        [EnumMember(Value = "table")]
        TableEnum = 1,

        /// <summary>
        /// Enum SubTableEnum for subTable
        /// </summary>
        [EnumMember(Value = "subTable")]
        SubTableEnum = 2
    }
}
