/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Os.Server.Models
{ 
        /// <summary>
        /// Gets or Sets NfcTagType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NfcTagType
        {
            
            /// <summary>
            /// Enum ProprietaryTagEnum for proprietaryTag
            /// </summary>
            [EnumMember(Value = "proprietaryTag")]
            ProprietaryTagEnum = 1,
            
            /// <summary>
            /// Enum NfcTagType1Enum for nfcTagType1
            /// </summary>
            [EnumMember(Value = "nfcTagType1")]
            NfcTagType1Enum = 2,
            
            /// <summary>
            /// Enum NfcTagType2Enum for nfcTagType2
            /// </summary>
            [EnumMember(Value = "nfcTagType2")]
            NfcTagType2Enum = 3,
            
            /// <summary>
            /// Enum NfcTagType3Enum for nfcTagType3
            /// </summary>
            [EnumMember(Value = "nfcTagType3")]
            NfcTagType3Enum = 4,
            
            /// <summary>
            /// Enum NfcTagType4Enum for nfcTagType4
            /// </summary>
            [EnumMember(Value = "nfcTagType4")]
            NfcTagType4Enum = 5,
            
            /// <summary>
            /// Enum MifareTagEnum for mifareTag
            /// </summary>
            [EnumMember(Value = "mifareTag")]
            MifareTagEnum = 6
        }
}
