/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Os.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaySubTables : PayBase, IEquatable<PaySubTables>
    { 
        /// <summary>
        /// Array of sub table ids. The sum of the amount of all these subtables together will be paid by  Payments. NOTE: The sub table IDs can only be from the same table. An error will be returned if they are from more then one table.
        /// </summary>
        /// <value>Array of sub table ids. The sum of the amount of all these subtables together will be paid by  Payments. NOTE: The sub table IDs can only be from the same table. An error will be returned if they are from more then one table.</value>
        [Required]
        [DataMember(Name="subTableIds")]
        public List<string> SubTableIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaySubTables {\n");
            sb.Append("  SubTableIds: ").Append(SubTableIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaySubTables)obj);
        }

        /// <summary>
        /// Returns true if PaySubTables instances are equal
        /// </summary>
        /// <param name="other">Instance of PaySubTables to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaySubTables other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SubTableIds == other.SubTableIds ||
                    SubTableIds != null &&
                    SubTableIds.SequenceEqual(other.SubTableIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SubTableIds != null)
                    hashCode = hashCode * 59 + SubTableIds.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaySubTables left, PaySubTables right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaySubTables left, PaySubTables right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
