/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Os.Server.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaySubTables : IEquatable<PaySubTables>
    {
        /// <summary>
        /// The payments to be executed on the amount sum we get from all the sub tables in SubTableIds. Special Case: Empty payments / Payments omitted is used to close empty tables.
        /// </summary>
        /// <value>The payments to be executed on the amount sum we get from all the sub tables in SubTableIds. Special Case: Empty payments / Payments omitted is used to close empty tables.</value>
        [DataMember(Name = "payments")]
        public List<Payment> Payments { get; set; }

        /// <summary>
        /// Identifies the printer to send the receipt print job to.  example: &#39;local://1&#39; check GET /api/v2/data/Printers to get a list of supported print targets
        /// </summary>
        /// <value>Identifies the printer to send the receipt print job to.  example: &#39;local://1&#39; check GET /api/v2/data/Printers to get a list of supported print targets</value>
        [DataMember(Name = "printer")]
        public string Printer { get; set; }

        /// <summary>
        /// Array of sub table ids. The sum of the amount of all these subtables together will be paid by  Payments. NOTE: The sub table IDs can only be from the same table. An error will be returned if they are from more then one table.
        /// </summary>
        /// <value>Array of sub table ids. The sum of the amount of all these subtables together will be paid by  Payments. NOTE: The sub table IDs can only be from the same table. An error will be returned if they are from more then one table.</value>
        [Required]
        [DataMember(Name = "subTableIds")]
        public List<string> SubTableIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaySubTables {\n");
            sb.Append("  Payments: ").Append(Payments).Append("\n");
            sb.Append("  Printer: ").Append(Printer).Append("\n");
            sb.Append("  SubTableIds: ").Append(SubTableIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaySubTables)obj);
        }

        /// <summary>
        /// Returns true if PaySubTables instances are equal
        /// </summary>
        /// <param name="other">Instance of PaySubTables to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaySubTables other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Payments == other.Payments ||
                    Payments != null &&
                    Payments.SequenceEqual(other.Payments)
                ) &&
                (
                    Printer == other.Printer ||
                    Printer != null &&
                    Printer.Equals(other.Printer)
                ) &&
                (
                    SubTableIds == other.SubTableIds ||
                    SubTableIds != null &&
                    SubTableIds.SequenceEqual(other.SubTableIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Payments != null)
                    hashCode = hashCode * 59 + Payments.GetHashCode();
                if (Printer != null)
                    hashCode = hashCode * 59 + Printer.GetHashCode();
                if (SubTableIds != null)
                    hashCode = hashCode * 59 + SubTableIds.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PaySubTables left, PaySubTables right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaySubTables left, PaySubTables right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
