/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace Os.Server.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PreAuthResult : IEquatable<PreAuthResult>
    {
        /// <summary>
        /// Gets or Sets AuthMedia
        /// </summary>
        [DataMember(Name = "authMedia")]
        public List<PreAuthMedium> AuthMedia { get; set; }

        /// <summary>
        /// If set a popup dialog is presented to the user before the user can continue. Supported types: \&quot;ok\&quot; and \&quot;accept\&quot;.
        /// </summary>
        /// <value>If set a popup dialog is presented to the user before the user can continue. Supported types: \&quot;ok\&quot; and \&quot;accept\&quot;.</value>
        [DataMember(Name = "dialog")]
        public Object Dialog { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PreAuthResult {\n");
            sb.Append("  AuthMedia: ").Append(AuthMedia).Append("\n");
            sb.Append("  Dialog: ").Append(Dialog).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PreAuthResult)obj);
        }

        /// <summary>
        /// Returns true if PreAuthResult instances are equal
        /// </summary>
        /// <param name="other">Instance of PreAuthResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PreAuthResult other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    AuthMedia == other.AuthMedia ||
                    AuthMedia != null &&
                    AuthMedia.SequenceEqual(other.AuthMedia)
                ) &&
                (
                    Dialog == other.Dialog ||
                    Dialog != null &&
                    Dialog.Equals(other.Dialog)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (AuthMedia != null)
                    hashCode = hashCode * 59 + AuthMedia.GetHashCode();
                if (Dialog != null)
                    hashCode = hashCode * 59 + Dialog.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PreAuthResult left, PreAuthResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PreAuthResult left, PreAuthResult right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
