/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace Os.Server.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ToolbarOrderConfig : IEquatable<ToolbarOrderConfig>
    {
        /// <summary>
        /// Configuration of the single buttons in the toolbar. The buttons will be shown in order of this list in the toolbar. If a screen has a back button this button is not configurable and is always shown at the beginning of the toolbar.             
        /// </summary>
        /// <value>Configuration of the single buttons in the toolbar. The buttons will be shown in order of this list in the toolbar. If a screen has a back button this button is not configurable and is always shown at the beginning of the toolbar.             </value>
        [DataMember(Name = "buttons")]
        public List<TBOrderConfig> Buttons { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ToolbarOrderConfig {\n");
            sb.Append("  Buttons: ").Append(Buttons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ToolbarOrderConfig)obj);
        }

        /// <summary>
        /// Returns true if ToolbarOrderConfig instances are equal
        /// </summary>
        /// <param name="other">Instance of ToolbarOrderConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ToolbarOrderConfig other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Buttons == other.Buttons ||
                    Buttons != null &&
                    Buttons.SequenceEqual(other.Buttons)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Buttons != null)
                    hashCode = hashCode * 59 + Buttons.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ToolbarOrderConfig left, ToolbarOrderConfig right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ToolbarOrderConfig left, ToolbarOrderConfig right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
