/*
 * NT.Access
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Runtime.Serialization;
using System.Text;

namespace Nt.Access.Models
{
    /// <summary>
    /// credit object
    /// </summary>
    [DataContract]
    public partial class Credit : IEquatable<Credit>
    {
        /// <summary>
        /// credit balance (*100)
        /// </summary>
        /// <value>credit balance (*100)</value>
        [DataMember(Name = "amount")]
        public int? Amount { get; set; }

        /// <summary>
        /// credit balance at opening (*100)
        /// </summary>
        /// <value>credit balance at opening (*100)</value>
        [DataMember(Name = "openingAmount")]
        public int? OpeningAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Credit {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  OpeningAmount: ").Append(OpeningAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            //return JsonConvert.SerializeObject(this, Formatting.Indented);
            return System.Text.Json.JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Credit)obj);
        }

        /// <summary>
        /// Returns true if Credit instances are equal
        /// </summary>
        /// <param name="other">Instance of Credit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Credit other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) &&
                (
                    OpeningAmount == other.OpeningAmount ||
                    OpeningAmount != null &&
                    OpeningAmount.Equals(other.OpeningAmount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                if (OpeningAmount != null)
                    hashCode = hashCode * 59 + OpeningAmount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(Credit left, Credit right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Credit left, Credit right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
