/*
 * NT.Access
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace Nt.Booking.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class BookingApiController : ControllerBase
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="mediumId">xxxyyy</param>
        /// <response code="200"></response>
        /// <response code="400"></response>
        [HttpGet]
        [Route("/api/v1/mediums/{mediumId}")]
        public virtual IActionResult GetMedium([FromRoute][Required]string mediumId)
        {
            try
            {
                var mediumInformation = NtBooking.BookingSystem.GetMediumInformation(mediumId);
                return new ObjectResult(mediumInformation);
            }
            catch (BookingException ex)
            {
                return GeExceptiontResponse(ex);
            }
            catch (Exception ex)
            {
                return GeExceptiontResponse(ex);
            }
        }

        /// <summary>
        /// 
        /// </summary>

        /// <param name="mediumId">returns a list of mediums / chips / rooms / vouchers</param>
        /// <response code="200"></response>
        /// <response code="400"></response>
        [HttpGet]
        [Route("/api/v1/mediums/")]
        public virtual IActionResult GetMediums()
        {
            try
            {
                var mediumInformation = NtBooking.BookingSystem.GetMediumInformation();
                return new ObjectResult(mediumInformation);
            }
            catch (BookingException ex)
            {
                return GeExceptiontResponse(ex);
            }
            catch (Exception ex)
            {
                return GeExceptiontResponse(ex);
            }
        }

        /// <summary>
        /// Get the status of the host / POS. This will be regularly called by clients to detect status changes (like host / POS restarts)
        /// </summary>
        /// <param name="mediumId">id of the medium</param>
        /// <param name="data"></param>
        /// <response code="200"></response>
        [HttpPost]
        [Route("/api/v1/mediums/{mediumId}/payments")]
        public virtual IActionResult MediumPayment([FromRoute][Required]string mediumId, [FromBody]Models.Payment payment)
        {
            try
            {
                var booking = NtBooking.BookingSystem.Pay();
                return new ObjectResult(booking);
            }
            catch (BookingException ex)
            {
                return GeExceptiontResponse(ex);
            }
            catch (Exception ex)
            {
                return GeExceptiontResponse(ex);
            }
        }

        /// <summary>
        /// Get the status of the host / POS. This will be regularly called by clients to detect status changes (like host / POS restarts)
        /// </summary>
        /// <param name="mediumId">xxxyyy</param>
        /// <param name="data"></param>
        /// <response code="200"></response>
        [HttpPost]
        [Route("/api/v1/mediums/{mediumId}/cancellations")]
        public virtual IActionResult MediumCancellation([FromRoute][Required]string mediumId, [FromBody]Models.Cancellation cancellation)
        {
            try
            {
                var booking = NtBooking.BookingSystem.Pay();
                return new ObjectResult(booking);
            }
            catch (BookingException ex)
            {
                return GeExceptiontResponse(ex);
            }
            catch (Exception ex)
            {
                return GeExceptiontResponse(ex);
            }
        }

        #region private methods

        private ObjectResult GeExceptiontResponse(BookingException ex)
        {
            Nt.Logging.Log.Server.Error(ex, HttpContext.Request.Path + "|");
            var error = new Models.Error();
            error.Message = ex.Message;
            error.UserMessage = ex.UserMessage;
            error.PartnerCode = ex.PartnerCode;
            error.PartnerMessage = ex.PartnerMessage;
            error.Id = ex.Code;

            return StatusCode(ex.HttpStatusCode, error);
        }

        private ObjectResult GeExceptiontResponse(Exception ex)
        {
            Nt.Logging.Log.Server.Error(ex, HttpContext.Request.Path + "|");
            var error = new Models.Error();
            error.Message = ex.Message;
            //500
            return StatusCode(StatusCodes.Status500InternalServerError, error);
        }

        #endregion

    }
}
