/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Novum.Data.Models.Os
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OrderLineQuanity : IEquatable<OrderLineQuanity>
    {
        /// <summary>
        /// The ID of the orderline to be paid.
        /// </summary>
        /// <value>The ID of the orderline to be paid.</value>
        [DataMember(Name = "orderLineId")]
        public string OrderLineId { get; set; }

        /// <summary>
        /// The quantity of the orderline in question that should be paid. IMPORTANT: This can be the full orderline or just a part of it.
        /// </summary>
        /// <value>The quantity of the orderline in question that should be paid. IMPORTANT: This can be the full orderline or just a part of it.</value>
        // [Required]
        [DataMember(Name = "quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderLineQuanity {\n");
            sb.Append("  OrderLineId: ").Append(OrderLineId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OrderLineQuanity)obj);
        }

        /// <summary>
        /// Returns true if OrderLineQuanity instances are equal
        /// </summary>
        /// <param name="other">Instance of OrderLineQuanity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderLineQuanity other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    OrderLineId == other.OrderLineId ||
                    OrderLineId != null &&
                    OrderLineId.Equals(other.OrderLineId)
                ) &&
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (OrderLineId != null)
                    hashCode = hashCode * 59 + OrderLineId.GetHashCode();
                if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(OrderLineQuanity left, OrderLineQuanity right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OrderLineQuanity left, OrderLineQuanity right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
