#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/NovumPosServerStup/ && \
    dotnet build src/NovumPosServerStup/ && \
    echo "Now, run the following to start the project: dotnet run -p src/NovumPosServerStup/NovumPosServerStup.csproj --launch-profile web"
