name: novum_web_client
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  loading: ^1.0.1
  flutter_spinkit: "^3.1.0"
  async: ^2.2.0
  grpc: ^1.0.3
  protobuf: ^0.13.15
  auto_size_text: ^2.0.2+1
  font_awesome_flutter: ^8.0.1

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
