/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Os.Server.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ActionButtonOnSuccess : IEquatable<ActionButtonOnSuccess>
    {
        /// <summary>
        /// Take a specific OrderSolution action.
        /// </summary>
        /// <value>Take a specific OrderSolution action.</value>
        [Required]
        [DataMember(Name = "exec")]
        public Object Exec { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ActionButtonOnSuccess {\n");
            sb.Append("  Exec: ").Append(Exec).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ActionButtonOnSuccess)obj);
        }

        /// <summary>
        /// Returns true if ActionButtonOnSuccess instances are equal
        /// </summary>
        /// <param name="other">Instance of ActionButtonOnSuccess to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ActionButtonOnSuccess other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Exec == other.Exec ||
                    Exec != null &&
                    Exec.Equals(other.Exec)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Exec != null)
                    hashCode = hashCode * 59 + Exec.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ActionButtonOnSuccess left, ActionButtonOnSuccess right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ActionButtonOnSuccess left, ActionButtonOnSuccess right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
