/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace Os.Server.Models
{
    /// <summary>
    /// Gets or Sets BarcodeIlluminationMode
    /// </summary>

    public enum BarcodeIlluminationMode
    {

        /// <summary>
        /// Enum OffEnum for off
        /// </summary>

        OffEnum,

        /// <summary>
        /// Enum AimerEnum for aimer
        /// </summary>

        AimerEnum,

        /// <summary>
        /// Enum IlluminationEnum for illumination
        /// </summary>

        IlluminationEnum,

        /// <summary>
        /// Enum AimerAndIlluminationAlternatingEnum for aimerAndIlluminationAlternating
        /// </summary>

        AimerAndIlluminationAlternatingEnum,

        /// <summary>
        /// Enum AimerAndIlluminationEnum for aimerAndIllumination
        /// </summary>

        AimerAndIlluminationEnum
    }
}
