/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Os.Server.Models
{
    /// <summary>
    /// Defines the input parameters for reading media via the NFC hardware reader. Supported media types depend on the actual device but typically these are NFC compatible tags or order cards base on the ISO 14443 A+b and similar standards. IMORTANT: At the moment only reading the UID of the tags are supported
    /// </summary>
    [DataContract]
    public partial class NfcInput : IEquatable<NfcInput>
    {
        /// <summary>
        /// true to force query the ISO UID from the read tag. NOTE: This is currently the only valid data type and must be set to true.
        /// </summary>
        /// <value>true to force query the ISO UID from the read tag. NOTE: This is currently the only valid data type and must be set to true.</value>
        [Required]
        [DataMember(Name = "isoUID")]
        public bool? IsoUID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NfcInput {\n");
            sb.Append("  IsoUID: ").Append(IsoUID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((NfcInput)obj);
        }

        /// <summary>
        /// Returns true if NfcInput instances are equal
        /// </summary>
        /// <param name="other">Instance of NfcInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NfcInput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    IsoUID == other.IsoUID ||
                    IsoUID != null &&
                    IsoUID.Equals(other.IsoUID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (IsoUID != null)
                    hashCode = hashCode * 59 + IsoUID.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(NfcInput left, NfcInput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(NfcInput left, NfcInput right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
