/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Os.Server.Models
{
    /// <summary>
    /// Gets or Sets NumberOfCoversMode
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum NumberOfCoversMode
    {

        /// <summary>
        /// Enum DisabledEnum for disabled
        /// </summary>
        [EnumMember(Value = "disabled")]
        DisabledEnum = 1,

        /// <summary>
        /// Enum RequiredEnum for required
        /// </summary>
        [EnumMember(Value = "required")]
        RequiredEnum = 2
    }
}
