/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace Os.Server.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PayOrderLines : PayBase, IEquatable<PayOrderLines>
    {
        /// <summary>
        /// List of order line payments that represent the order lines (-parts) that will be paid with this set.
        /// </summary>
        /// <value>List of order line payments that represent the order lines (-parts) that will be paid with this set.</value>
        [DataMember(Name = "paidLines")]
        public List<OrderLineQuantity> PaidLines { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PayOrderLines {\n");
            sb.Append("  PaidLines: ").Append(PaidLines).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PayOrderLines)obj);
        }

        /// <summary>
        /// Returns true if PayOrderLines instances are equal
        /// </summary>
        /// <param name="other">Instance of PayOrderLines to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PayOrderLines other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PaidLines == other.PaidLines ||
                    PaidLines != null &&
                    PaidLines.SequenceEqual(other.PaidLines)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (PaidLines != null)
                    hashCode = hashCode * 59 + PaidLines.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PayOrderLines left, PayOrderLines right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PayOrderLines left, PayOrderLines right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
