/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Os.Server.Models
{
    /// <summary>
    /// Gets or Sets TBPaymentType
    /// </summary>
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum TBPaymentType
    {

        /// <summary>
        /// Enum CalculatorEnum for calculator
        /// </summary>
        [EnumMember(Value = "calculator")]
        CalculatorEnum = 1,

        /// <summary>
        /// Enum PrinterSelectionEnum for printerSelection
        /// </summary>
        [EnumMember(Value = "printerSelection")]
        PrinterSelectionEnum = 2,

        /// <summary>
        /// Enum TipEnum for tip
        /// </summary>
        [EnumMember(Value = "tip")]
        TipEnum = 3
    }
}
