/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Os.Server.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TBTableSelectConfig : IEquatable<TBTableSelectConfig>
    {
        /// <summary>
        /// Get / set the type of this toolbar.
        /// </summary>
        /// <value>Get / set the type of this toolbar.</value>
        [Required]
        [DataMember(Name = "type")]
        public Object Type { get; set; }

        /// <summary>
        /// The detailed configuration of action buttons (&#x3D; when type &#x3D;&#x3D; \&quot;action\&quot;)
        /// </summary>
        /// <value>The detailed configuration of action buttons (&#x3D; when type &#x3D;&#x3D; \&quot;action\&quot;)</value>
        [DataMember(Name = "action")]
        public Object Action { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TBTableSelectConfig {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TBTableSelectConfig)obj);
        }

        /// <summary>
        /// Returns true if TBTableSelectConfig instances are equal
        /// </summary>
        /// <param name="other">Instance of TBTableSelectConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TBTableSelectConfig other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) &&
                (
                    Action == other.Action ||
                    Action != null &&
                    Action.Equals(other.Action)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                if (Action != null)
                    hashCode = hashCode * 59 + Action.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(TBTableSelectConfig left, TBTableSelectConfig right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TBTableSelectConfig left, TBTableSelectConfig right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
