/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Novum.Data.Os
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ModifierChoice : IEquatable<ModifierChoice>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ReceiptName
        /// </summary>
        [DataMember(Name="receiptName")]
        public string ReceiptName { get; set; }

        /// <summary>
        /// Gets or Sets DefaultAmount
        /// </summary>
        [DataMember(Name="defaultAmount")]
        public int? DefaultAmount { get; set; }

        /// <summary>
        /// Gets or Sets MinAmount
        /// </summary>
        [DataMember(Name="minAmount")]
        public int? MinAmount { get; set; }

        /// <summary>
        /// Gets or Sets MaxAmount
        /// </summary>
        [DataMember(Name="maxAmount")]
        public int? MaxAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModifierChoice {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ReceiptName: ").Append(ReceiptName).Append("\n");
            sb.Append("  DefaultAmount: ").Append(DefaultAmount).Append("\n");
            sb.Append("  MinAmount: ").Append(MinAmount).Append("\n");
            sb.Append("  MaxAmount: ").Append(MaxAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ModifierChoice)obj);
        }

        /// <summary>
        /// Returns true if ModifierChoice instances are equal
        /// </summary>
        /// <param name="other">Instance of ModifierChoice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModifierChoice other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    ReceiptName == other.ReceiptName ||
                    ReceiptName != null &&
                    ReceiptName.Equals(other.ReceiptName)
                ) && 
                (
                    DefaultAmount == other.DefaultAmount ||
                    DefaultAmount != null &&
                    DefaultAmount.Equals(other.DefaultAmount)
                ) && 
                (
                    MinAmount == other.MinAmount ||
                    MinAmount != null &&
                    MinAmount.Equals(other.MinAmount)
                ) && 
                (
                    MaxAmount == other.MaxAmount ||
                    MaxAmount != null &&
                    MaxAmount.Equals(other.MaxAmount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (ReceiptName != null)
                    hashCode = hashCode * 59 + ReceiptName.GetHashCode();
                    if (DefaultAmount != null)
                    hashCode = hashCode * 59 + DefaultAmount.GetHashCode();
                    if (MinAmount != null)
                    hashCode = hashCode * 59 + MinAmount.GetHashCode();
                    if (MaxAmount != null)
                    hashCode = hashCode * 59 + MaxAmount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ModifierChoice left, ModifierChoice right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ModifierChoice left, ModifierChoice right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
