x-generator: NSwag v13.1.2.0 (NJsonSchema v10.0.24.0 (Newtonsoft.Json v12.0.0.0))
swagger: '2.0'
info:
  title: NT.Booking
  version: 0.0.0
host: '10.0.0.136:12346'
schemes:
  - http
paths:
  '/api/v1/mediums/{mediumId}':
    get:
      tags:
        - medium
      operationId: getMediumInformation
      parameters:
        - type: string
          name: mediumId
          description: returns information of a certain medium / chip / room / voucher
          in: path
          required: true
          x-nullable: false
      produces:
        - application/json
      responses:
        '200':
          x-nullable: false
          description: ''
          schema:
            $ref: '#/definitions/InformationResponse'
        '400':
          x-nullable: false
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/api/v1/mediums/':
    get:
      tags:
        - medium
      operationId: getAllMedium
      parameters:
        - type: string
          name: mediumId
          description: returns a list of mediums / chips / rooms / vouchers
          in: path
          required: true
          x-nullable: false
      produces:
        - application/json
      responses:
        '200':
          x-nullable: false
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/InformationResponse'
        '400':
          x-nullable: false
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/api/v1/mediums/{mediumId}/payments':
    post:
      tags:
        - medium
      summary: >-
        Get the status of the host / POS. This will be regularly called by
        clients to detect status changes (like host / POS restarts)
      operationId: postMediumPayment
      consumes:
        - application/json
      parameters:
        - type: string
          name: mediumId
          description: id of the medium
          in: path
          required: true
          x-nullable: false
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/PaymentRequest'
          x-nullable: false
      produces:
        - application/json
      responses:
        '200':
          x-nullable: false
          description: ''
          schema:
            $ref: '#/definitions/BookingResponse'
  '/api/v1/mediums/{mediumId}/cancellations':
    post:
      tags:
        - medium
      summary: >-
        Get the status of the host / POS. This will be regularly called by
        clients to detect status changes (like host / POS restarts)
      operationId: postMediumCancellation
      consumes:
        - application/json
      parameters:
        - type: string
          name: mediumId
          description: xxxyyy
          in: path
          required: true
          x-nullable: false
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/CancellationRequest'
          x-nullable: false
      produces:
        - application/json
      responses:
        '200':
          x-nullable: false
          description: ''
          schema:
            $ref: '#/definitions/BookingResponse'
definitions:
  InformationResponse:
    description: This object contains all Information of the medium
    type: object
    properties:
      owner: 
        $ref: '#/definitions/Owner'
      debit:
        $ref: '#/definitions/Debit'
      credit:
        $ref: '#/definitions/Credit'
      currency: 
        description: currency in ISO 4217 (EUR/CHF/GBP/USD/JPY/CNY/...)
        type: string
      discountType:
        description: type of discount
        type: string
  ErrorResponse:
    description: error object
    type: object
    properties:
      message:
        type: string
      bookingSystem:
        type: string
      bookingSystemMessage:
        type: string
      bookingSystemCode: 
        type: string
      DisplayMessage:
        type: string
  PaymentRequest:
    description: This object contains all information of the payment with a medium
    type: object
    properties:
      clientId:
        type: string
        description: ID of the requesting system
      clientName:
        type: string
        description: Name of the requesting system
      waiterId:
        type: string
        description: ID of the POS operator
      waiterName:
        type: string
        description: Name of the POS operator
      posId:
        type: string
        description: ID of the POS
      posName:
        type: string
        description: Name of the POS
      serviceAreaId:
        type: string
        description: ID of the service area
      serviceAreaName:
        type: string
        description: Name of the service area
      tableId:
        type: string
        description: ID of the table
      tableName:
        type: string
        description: Name of the table
      sale: 
        $ref: '#/definitions/Sales'
  Sales:
    description: This object contains all sales
    type: array
    items:
      $ref: '#/definitions/Sale'
  Sale:
    description: This object contains all information of a sale
    type: object
    properties:
      billId:
        type: string
        description: ID of the bill
      timestamp:
        type: string
        format: date-time
        description: Creation date and time of the bill
      currency:
        type: string
        description: Currency of the bill
      payment: 
        $ref: '#/definitions/Payments'
      article: 
        $ref: '#/definitions/Articles'
  Payments:
    description: This object contains all payments
    type: array
    items:
      $ref: '#/definitions/Payment'
  Payment:
    description: This object contains all information of a payment
    type: object
    properties:
      paymentTypeId:
        type: string
        description: ID of the payment method
      paymentTypeName:
        type: string
        description: Name of the payment method
      amount:
        type: integer
        description: Amount of the payment multiplied by 100
      tip:
        type: integer
        description: Amount of the tip multiplied by 100
  Articles:
    description: This object contains all articles
    type: array
    items:
      $ref: '#/definitions/Article'
  Article:
    description: This object contains all information of an article
    type: object
    properties:
      articleId:
        type: string
        description: ID of the article
      articleName:
        type: string
        description: Name of the article
      quantity:
        type: integer
        description: Quantity multiplied by 100 
      quantityUnit:
        type: string
        description: Unit of the quantity
      articleGroupId:
        type: string
        description: ID of the article group
      articleGroupName:
        type: string
        description: Name of the article group
      unitPrice:
        type: integer
        description: Unit price multiplied by 100 including tax
      taxRate:
        type: integer
        description: Tax rate multiplied by 100 
      discountAmount:
        type: integer
        description: discount multiplied by 100 (discount to the total amount = unitPrice * quantity)
      discountGroupId:
        type: string
        description: ID of the discount group
      discountGroupName:
        type: string
        description: Name of the discount group
  CancellationRequest:
    description: This object contains all information of the cancellation with a medium
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  BookingResponse:
    description: This object contains all information of a booking (payment/cancellation)
    type: object
    properties:
      id:
        type: string
      DisplayMessage:
        type: string
  Debit: 
    description: debit object 
    type: object
    properties:
      amount: 
        description: debt amount/debt level (*100)
        type: integer
        format: int32
      limit:
        description: debt limit (*100)
        type: integer
        format: int32
      limitWarning:
        description: warning of debt limit (*100)
        type: integer
        format: int32
  Credit: 
    description: credit object 
    type: object
    properties:
      amount:
        description: credit balance (*100)
        type: integer
        format: int32
      openingAmount:
        description: credit balance at opening (*100)
        type: integer
        format: int32
  Owner: 
    description: owner of the medium
    type: object
    properties:
      name:
        description: name of the owner (John Doe)
        type: string  
