/*
 * OrderSolution HTTP API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.9.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using NovumPosServerStup.Attributes;
using NovumPosServerStup.Models;

namespace NovumPosServerStup.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class ActionssubtablesApiController : Controller
    { 
        /// <summary>
        /// Create a new subtable.
        /// </summary>
        
        /// <param name="tableId">The table this sub table is created for.</param>
        /// <response code="201"></response>
        [HttpPost]
        [Route("/api/v2/actions/SubTables/Create")]
        [ValidateModelState]
        [SwaggerOperation("SubTablesCreate")]
        [SwaggerResponse(statusCode: 201, type: typeof(SubTable), description: "")]
        public virtual IActionResult SubTablesCreate([FromQuery]string tableId)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(SubTable));

            string exampleJson = null;
            exampleJson = "{\r\n  \"name\" : \"name\",\r\n  \"isSelected\" : true,\r\n  \"id\" : \"id\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<SubTable>(exampleJson)
            : default(SubTable);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
