name: Nt.Booking Deploy

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
  
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  PLATFORM: windows-latest

jobs:
  build:
    runs-on: ${{platform}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Nt.Booking dependencies
      run: dotnet restore src/Services/Nt.Booking/Nt.Booking.csproj
    - name: Build Nt.Booking
      run: dotnet build src/Services/Nt.Booking/Nt.Booking.csproj -c Release --no-restore

  test:
    needs: build
    runs-on: ${{platform}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: 
      run: dotnet test src/Services/Nt.Booking/Nt.Booking.csproj

  deploy:
    needs: test
    runs-on: ${{platform}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: 
      run: dotnet publish src/Services/Nt.Booking/Nt.Booking.csproj -c Release -o publish/windows
    



    


    
